# Generated by Django 4.0.4 on 2022-05-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_users_book_or_buy_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='identifierـcode',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='Identifier code'),
        ),
    ]
