# Generated by Django 4.0.4 on 2022-05-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_users_identifierـcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='benـkala',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ben Kala'),
        ),
        migrations.AddField(
            model_name='users',
            name='commission',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Commission'),
        ),
        migrations.AddField(
            model_name='users',
            name='walletـbalance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Wallet balance'),
        ),
    ]
