# Generated by Django 4.0.4 on 2022-05-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Derakhti', '0020_rename_deposit_request_depositrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='derakhtiproductsorders',
            name='price_drsd',
            field=models.IntegerField(blank=True, null=True, verbose_name='price_drsd'),
        ),
    ]
