# Generated by Django 4.0.4 on 2022-05-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Derakhti', '0021_derakhtiproductsorders_price_drsd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rusers',
            name='main',
        ),
        migrations.RemoveField(
            model_name='rusers',
            name='user',
        ),
        migrations.DeleteModel(
            name='Lusers',
        ),
        migrations.DeleteModel(
            name='Rusers',
        ),
    ]
