# Generated by Django 4.0.4 on 2022-05-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Derakhti', '0023_canelproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canelproduct',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
