# Generated by Django 4.0.4 on 2022-05-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Derakhti', '0024_alter_canelproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='canelproduct',
            name='mobile1',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='mobile1'),
        ),
        migrations.AddField(
            model_name='canelproduct',
            name='mobile2',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='mobile2'),
        ),
    ]
