# Generated by Django 4.0.4 on 2022-05-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SlidersImage', verbose_name='Image')),
                ('url', models.CharField(max_length=999, verbose_name='URl')),
            ],
        ),
    ]
